Project/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Project.Models;
using System.Net;
using System.Data.Entity;
using Microsoft.Reporting.WebForms;

namespace Exam__.Controllers
{
    public class ExamController : Controller
    {
        // GET: Exam
        public ActionResult Index()
        {
            DBmodel DB = new DBmodel();

            List<subject> subjectList = DB.subjects.ToList();
            ViewBag.subList = new SelectList(subjectList, "subject_id", "subject1");

            List<GradeList> gradeList = DB.GradeLists.ToList();
            ViewBag.grList = new SelectList(gradeList, "ID", "Grade");

            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file, ExamUpload ex)
        {

            if (!ModelState.IsValid)
            {


                return new JsonResult { Data = "File not upload" };


            }
            else
            {
                DBmodel DB = new DBmodel();
                Exam2 log = new Exam2();

                var subject = DB.subjects.Where(m => m.subject_id == ex.subject_id).Select(u => new { subject = u.subject1 }).Single();
                var grade = DB.GradeLists.Where(m => m.ID == ex.grade_id).Select(u => new { grade = u.Grade}).Single();

                string path = Server.MapPath("~/App_Data/File/");
                string fileName = Path.GetFileName(file.FileName);

                string fullPath = Path.Combine(path, fileName);

                log.FileName = fileName;
                log.FilePath = fullPath;
                log.Grade = grade.grade;
                log.Subject = subject.subject;
                log.TeacherName = "ASDF";


                DB.Exam2.Add(log);
                DB.SaveChanges();


                file.SaveAs(fullPath);
                return RedirectToAction("ViewList");
            }
        }

        public ActionResult ViewList()
        {
            DBmodel db = new DBmodel();

            List<Exam2> files = db.Exam2.ToList();

            return View(files);

        }
        public FileResult DownloadFile(string FileName)
        {
            var directory = new DirectoryInfo(Server.MapPath("~/App_Data/File"));

            string path = directory.FullName;
            byte[] fileBytes = System.IO.File.ReadAllBytes(@path + "\\" + FileName);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, FileName);

        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBmodel db = new DBmodel();
            Exam2 file = db.Exam2.Find(id);

            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);

        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteSucces(int id)
        {
            DBmodel db = new DBmodel();
            Exam2 file = db.Exam2.Find(id);


            Exam2 teacher = db.Exam2.Find(id);
            db.Exam2.Remove(teacher);
            db.SaveChanges();

            var directory = new DirectoryInfo(Server.MapPath("~/App_Data/File"));
            string getFile = directory.FullName + "\\" + file.FileName;
            System.IO.File.Delete(getFile);

            //db.Exam2.Remove(file);
            db.SaveChanges();

            return RedirectToAction("ViewList");
        }
        public ActionResult Edit(int? id)
        {
            DBmodel db = new DBmodel();
            Exam2 file = db.Exam2.Find(id);
            ExamUpload model = new ExamUpload();

            model.ExamID = file.ExamID;
            model.subject1 = file.Subject;
            model.grade1 = file.Grade;
            model.TeacherName = file.TeacherName;
            model.FileName = file.FileName;
            model.FilePath = file.FilePath;


            List<subject> subjectList = db.subjects.ToList();
            ViewBag.subList = new SelectList(subjectList, "subject_id", "subject1");

            List<GradeList> gradeList = db.GradeLists.ToList();
            ViewBag.grList = new SelectList(gradeList, "ID", "Grade");

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(int id, ExamUpload model)
        {
            DBmodel db = new DBmodel();
            Exam2 exam = db.Exam2.Find(id);

            if (ModelState.IsValid)
            {

                string oldName = exam.FileName;
                exam.FileName = model.FileName;

                int grade2 = model.grade_id;
                int subject2 = model.subject_id;

                var subject = db.subjects.Where(m => m.subject_id == subject2).Select(u => new { subject = u.subject1 }).Single();
                var grade = db.GradeLists.Where(m => m.ID == grade2).Select(u => new { grade = u.Grade }).Single();

                //file.FilePath = fullPath;
                exam.Grade = grade.grade;
                exam.Subject = subject.subject;

                db.Entry(exam).State = EntityState.Modified;
                db.SaveChanges();

                int ExamID = model.ExamID;

                Exam2 teacher = db.Exam2.Find(id);

                teacher.ExamID = model.ExamID;

                db.Entry(teacher).State = EntityState.Modified;
                db.SaveChanges();

                ChangeFileName(ExamID, model.FileName, oldName);

                return RedirectToAction("ViewList");
            }
            else
            {

                List<GradeList> gradeList = db.GradeLists.ToList();
                ViewBag.grList = new SelectList(gradeList, "ID", "Grade");

                List<subject> subjectList = db.subjects.ToList();
                ViewBag.subList = new SelectList(subjectList, "subject_id", "subject1");




                return View(model);
            }

        }
        public void ChangeFileName(int Exam_ID, string FileName, string oldName)
        {
            DBmodel db = new DBmodel();

            Exam2 file = db.Exam2.Find(Exam_ID);

            var directory = new DirectoryInfo(Server.MapPath("~/App_Data/File"));
            string getFile = directory.FullName + "\\" + oldName;


            System.IO.File.Move(getFile, directory.FullName + "\\" + FileName);

            string path = file.FilePath;

            path = "C:\\Users\\Halo\\source\\repos\\Exam__\\Exam__\\App_Data\\File" + FileName;

            file.FilePath = path;
            db.Entry(file).State = EntityState.Modified;
            db.SaveChanges();
        }
        public ActionResult Reports()
        {
            DBmodel db = new DBmodel();
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/ExamReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "Exam2DataSet";
            reportDataSource.Value = db.Exam2.ToList();
            localReport.DataSources.Add(reportDataSource);
            string mimeType;
            string encoding;
            string fileNameExtenction = "pdf";
            string[] streams;
            Warning[] warnings;
            byte[] renderedByte;
            renderedByte = localReport.Render("PDF", "", out mimeType, out encoding, out fileNameExtenction, out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment:filename = Exam2_report." + fileNameExtenction);
            return File(renderedByte, fileNameExtenction);

        }


        ///--- Student ---///

        public ActionResult StudentViewList()
        {
            DBmodel db = new DBmodel();

            List<Exam2> files = db.Exam2.ToList();

            return View(files);
        }


    }
}

Project/Views/Exam/Delete.cshtml
@model Project.Models.Exam2

@{
    ViewBag.Title = "Delete";
}

<h2 class="text-center">Selected file details</h2>

<div class="table-bordered form-horizontal" style="border:double red">
    <div class="text-info " style="font-size:20px; margin-left:50px;">
        <div class="form-group">


            @Html.LabelFor(model => model.ExamID, new { @class = "control-label " })
            <div>


                @Html.DisplayFor(model => model.ExamID, new { @class = "form-control" })
            </div>

        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Subject, new { @class = "control-label" })
            <div>

                @Html.DisplayFor(model => model.Subject, new { @class = "form-control" })
            </div>


        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Grade, new { @class = "control-label" })
            <div>


                @Html.DisplayFor(model => model.Grade, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherName, new { @class = "control-label" })


            <div>
                @Html.DisplayFor(model => model.TeacherName, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, new { @class = "control-label" })


            <div>
                @Html.DisplayFor(model => model.FilePath, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FileName, new { @class = "control-label" })
            <div>


                @Html.DisplayFor(model => model.FileName, new { @class = "form-control" })
            </div>
        </div>
    </div>
</div>
<div style="margin-top:50px;">
    <button class=" btn btn-primary" data-toggle="modal" data-target="#delete">Delete</button>
</div>

<div class=" modal fade" id="delete" aria-hidden="true" tabindex="-1" role="dialog">
    <div class="modal-dialog ">
        <div class=" modal-content">
            <div class="modal-header ">
                <h3 class=" modal-title text-center">Do you want delete this File</h3>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="text-center">
                        <button type="submit" class="btn btn-danger text-center glyphicon glyphicon-trash"> <strong>Delete</strong> </button>

                    </div>
                }
                <div>
                    @Html.ActionLink("Back to List", "ViewList")
                </div>
            </div>

        </div>
    </div>

</div>

Project/Views/Exam/Edit.cshtml
@model Project.Models.ExamUpload
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Exam2</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ExamID)

    <div class="form-group">
        @Html.LabelFor(model => model.subject1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.subject_id, ViewBag.subList as SelectList, "Select Your Subject", htmlAttributes: new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.subject1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.grade1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.grade_id, ViewBag.grList as SelectList, "Select Your Grade", htmlAttributes: new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.grade1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-offset-2 col-md-8">

            <input type="file" name="file" />
            <br />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
</div>

}
<div>
    @Html.ActionLink("Back to List", "ViewList")
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
        $(document).ready(function () {
            $('#StartTime').datepicker({
                dateFormat: "dd/mm/yy",
                showStatus: true,
                showWeeks: true,
                currentText: 'Now',
                autoSize: true,
                gotoCurrent: true,
                showAnim: 'blind',
                highlightWeek: true
            });

        });
</script>

Project/Views/Exam/Index.cshtml
@model Project.Models.ExamUpload

@{
               

                ViewBag.Title = "Index";
}



@Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Insert</h4>
        <hr />
        @using (Html.BeginForm("Index", "Exam", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })




            <div class="form-group">
                @Html.LabelFor(model => model.subject1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.subject_id, ViewBag.subList as SelectList, "Select Your Subject", htmlAttributes: new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.subject1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.grade1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.grade_id, ViewBag.grList as SelectList, "Select Your Grade", htmlAttributes: new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.grade1, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="row">
                <div class="col-md-offset-2 col-md-8">

                    <input type="file" name="file" />
                    <br />


                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-10">
                            <input type="submit" value="Submit" class="btn btn-default" />
                        </div>
                    </div>






                </div>
            </div>

        }
        <div>
            @Html.ActionLink("Back to List", "ViewList")
        </div>
        <script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#StartTime').datepicker({
                    dateFormat: "dd/mm/yy",
                    showStatus: true,
                    showWeeks: true,
                    currentText: 'Now',
                    autoSize: true,
                    gotoCurrent: true,
                    showAnim: 'blind',
                    highlightWeek: true
                });

            });
        </script>

    </div>

Project/Views/Exam/StudentViewList.cshtml
@model IEnumerable<Project.Models.Exam2>

@{
    ViewBag.Title = "StudentViewList";
}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<span><br /></span>
<h2 class="text-center">Uploaded Files</h2>


<table class=" table table-bordered table-striped table-responsive-sm table-hover">

    <tr>

        <th>@Html.DisplayNameFor(model => model.Subject)</th>
        <th>@Html.DisplayNameFor(model => model.Grade)</th>
        <th>@Html.DisplayNameFor(model => model.TeacherName)</th>
        <th>@Html.DisplayNameFor(model => model.FileName)</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {


        <tr>
            <td>@Html.DisplayFor(modelItem => item.Subject)</td>
            <td>@Html.DisplayFor(modelItem => item.Grade)</td>
            <td>@Html.DisplayFor(modelItem => item.TeacherName)</td>
            <td>@Html.DisplayFor(modelItem => item.FileName)</td>
            <td>

                @Html.ActionLink("Download", "DownloadFile", new { FileName = item.FileName }, new { @class = "btn btn-success" }) 

            </td>
        </tr>
    }

</table>

Project/Views/Exam/ViewList.cshtml
@model IEnumerable<Project.Models.Exam2>

@{
    ViewBag.Title = "ViewList";
}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<span><br /></span>
<h2 class="text-center">Uploaded Files</h2>
@Html.ActionLink("Export to PDF", "Reports")

<table class=" table table-bordered table-striped table-responsive-sm table-hover">

    <tr>

        <th>@Html.DisplayNameFor(model => model.ExamID)</th>
        <th>@Html.DisplayNameFor(model => model.Subject)</th>
        <th>@Html.DisplayNameFor(model => model.Grade)</th>
        <th>@Html.DisplayNameFor(model => model.TeacherName)</th>
        <th>@Html.DisplayNameFor(model => model.FilePath)</th>
        <th>@Html.DisplayNameFor(model => model.FileName)</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {

        
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ExamID)
                </td>
                <td>@Html.DisplayFor(modelItem => item.Subject)</td>
                <td>@Html.DisplayFor(modelItem => item.Grade)</td>
                <td>@Html.DisplayFor(modelItem => item.TeacherName)</td>
                <td>@Html.DisplayFor(modelItem => item.FilePath)</td>
                <td>@Html.DisplayFor(modelItem => item.FileName)</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ExamID }, new { @class = "btn btn-success fa fa-edit" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ExamID }, new { @class = "btn btn-danger fa fas-trash-alt" })
                    
                </td>
            </tr>
        }

    </table>