Project/Controllers/TimetableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using System.Data.Entity;
using Microsoft.Reporting.WebForms;

namespace Timetable.Controllers
{
    public class TimetableController : Controller
    {
        public ActionResult Timetablehome()
        {
            
            return View();
        }

        // GET: Timetable
        public ActionResult TimetableList(string searching)
        {
            using(DBmodel tution = new DBmodel())
            {
               
                return View(tution.Timetables.Where(x=> x.Day.StartsWith(searching)|| searching == null).ToList());
            }
        }

        // GET: Timetable/Details/5
        public ActionResult TimetableDetails(int id)
        {
            using (DBmodel tution = new DBmodel())
            {
                return View(tution.Timetables.Where(x => x.classId == id).FirstOrDefault());
            }
        }

        // GET: Timetable/Create
        public ActionResult CreateTimetable()
        {
            DBmodel db = new DBmodel();

            List<TeacherList> list = db.TeacherLists.ToList();
            List<GradeList> grades = db.GradeLists.ToList();
            List<subject> subjects = db.subjects.ToList();

            ViewBag.teacherlist = new SelectList(list, "teacher_name", "teacher_name");
            ViewBag.Grades = new SelectList(grades, "Grade", "Grade");
            ViewBag.Subjects = new SelectList(subjects, "subject1", "subject1");

            return View();
        }

        // POST: Timetable/Create
        [HttpPost]
        public ActionResult CreateTimetable(Project.Models.Timetable timetable)
        {
            try
            {
                using (DBmodel tution = new DBmodel())
                {
                    ViewBag.IsError = false;
                    try
                    {
                        if (ModelState.IsValid)
                        {
                            SubjectDetail subject = new SubjectDetail();

                            var subje = tution.SubjectTBs.Where(m => m.SubjectName == timetable.Subject).Select(u => new { sub = u.SubjectCode }).Single();
                            
                            tution.Timetables.Add(timetable);
                            tution.SaveChanges();

                            subject.Hall = timetable.Hall;
                            subject.StartTime = timetable.StartTime;
                            subject.EndTime = timetable.EndTime;
                            subject.Day = timetable.Day;
                            subject.SubjectID = subje.sub;

                            tution.SubjectDetails.Add(subject);
                            tution.SaveChanges();

                            return RedirectToAction("TimetableList");
                        }
                    }
                    catch
                    {

                    }
                }
            }

            catch
            {
                DBmodel db = new DBmodel();

                List<TeacherList> list = db.TeacherLists.ToList();
                List<GradeList> grades = db.GradeLists.ToList();
                List<subject> subjects = db.subjects.ToList();

                ViewBag.teacherlist = new SelectList(list, "teacher_name", "teacher_name");
                ViewBag.Grades = new SelectList(grades, "Grade", "Grade");
                ViewBag.Subjects = new SelectList(subjects, "subject1", "subject1");

                return View();
            }
            return RedirectToAction("TimetableList");
        }
        

        // GET: Timetable/Edit/5
        public ActionResult EditTimetable(int id)
        {
            using (DBmodel tution = new DBmodel())
            {
                DBmodel db = new DBmodel();

                List<TeacherList> list = db.TeacherLists.ToList();
                List<GradeList> grades = db.GradeLists.ToList();
                List<subject> subjects = db.subjects.ToList();

                ViewBag.teacherlist = new SelectList(list, "teacher_name", "teacher_name");
                ViewBag.Grades = new SelectList(grades, "Grade", "Grade");
                ViewBag.Subjects = new SelectList(subjects, "subject1", "subject1");

                return View(tution.Timetables.Where(x => x.classId == id).FirstOrDefault());
            }
        }

        // POST: Timetable/Edit/5
        [HttpPost]
        public ActionResult EditTimetable(int id, Project.Models.Timetable timetable)
        {
            try
            {
                using (DBmodel tution = new DBmodel())
                {
                    //SubjectDetail subject = new SubjectDetail();

                    //string sub = tution.Timetables.Find(id).Subject.ToString();
                    timetable.classId = id;

                    tution.Entry(timetable).State = EntityState.Modified;
                    tution.SaveChanges();

                    //var subje = tution.SubjectTBs.Where(m => m.SubjectName == timetable.Subject).Select(u => new { sub = u.SubjectCode }).Single();

                    //subject.Hall = timetable.Hall;
                    //subject.StartTime = timetable.StartTime;
                    //subject.EndTime = timetable.EndTime;
                    //subject.Day = timetable.Day;
                    //subject.SubjectID = subje.sub;

                    //tution.Entry(subject).State = EntityState.Modified;
                    //tution.SaveChanges();

                    return RedirectToAction("TimetableList");
                }
                // TODO: Add update logic here

                
            }
            catch
            {

                return RedirectToAction("TimetableList");
            }
        }

        // GET: Timetable/Delete/5
        public ActionResult DeleteTimetable(int id)
        {
            using (DBmodel tution = new DBmodel())
            {
                return View(tution.Timetables.Where(x => x.classId == id).FirstOrDefault());
            }
        }

        // POST: Timetable/Delete/5
        [HttpPost]
        public ActionResult DeleteTimetable(int id, FormCollection collection)
        {
            Project.Models.Timetable timetable = new Project.Models.Timetable();
            try
            {
               
                using (DBmodel tution = new DBmodel())
                {
                    
                    timetable = tution.Timetables.Where(x => x.classId == id).FirstOrDefault();

                    //var subje = tution.SubjectTBs.Where(m => m.SubjectName == timetable.Subject).Select(u => new { sub = u.SubjectCode }).Single();


                    //SubjectDetail subject = tution.SubjectDetails.Where(x => x.SubjectID == subje.sub).FirstOrDefault();
                   
                    tution.Timetables.Remove(timetable);
                    tution.SaveChanges();

                    //tution.SubjectDetails.Remove(subject);
                    //tution.SaveChanges();
                }
                // TODO: Add update logic here

                return RedirectToAction("TimetableList");
            }
            catch
            {
                return View(timetable);
            }
        }
        public ActionResult Reports()
        {
            DBmodel tution = new DBmodel();
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/TimetableReport.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "TimetableDataSet";
            reportDataSource.Value = tution.Timetables.ToList();
            localReport.DataSources.Add(reportDataSource);
            string mimeType;
            string encoding;
            string fileNameExtenction = "pdf";
            string[] streams;
            Warning[] warnings;
            byte[] renderedByte;
            renderedByte = localReport.Render("pdf", "", out mimeType, out encoding, out fileNameExtenction, out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment:filename = timetable_report." + fileNameExtenction);
            return File(renderedByte, fileNameExtenction);

        }
    }


}

Project/Views/Timetable/CreateTimetable.cshtml
@model Project.Models.Timetable

@{
    ViewBag.Title = "CreateTimetable";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add New Class Details</h1>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel=" stylesheet" href="~/Content/bootstrap.css">
    <link rel=" stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
   
</head>




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal" style="font-size:15px">
    <br />

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Subject, ViewBag.Subjects as SelectList, "Select Subject", new { htmlAttributes = new { @class = "form-control col-md-10" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Grade, ViewBag.Grades as SelectList, "Select Grade", new { htmlAttributes = new { @class = "form-control col-md-10" } })
            @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TeacherName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TeacherName, ViewBag.teacherlist as SelectList, "Select Teacher", new { htmlAttributes = new { @class = "form-control col-md-10" } })
            @Html.ValidationMessageFor(model => model.TeacherName, "", new { @class = "text-danger" })
        </div>
    </div>
   
    <div class="form-group">
        @Html.LabelFor(model => model.Hall, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Hall", new List<SelectListItem>
                    {
                        new SelectListItem{ Text = "H1", Value ="H1"},
                        new SelectListItem{ Text = "H2", Value ="H2"},
                         new SelectListItem{ Text = "H3", Value ="H3"}
                    }, "Select Hall", new { htmlAttributes = new { @class = "dropdown dropdown-menu" } })
            @Html.ValidationMessageFor(model => model.Hall, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Day", new List<SelectListItem>
                    {
                        new SelectListItem{ Text = "Monday", Value ="Mon"},
                        new SelectListItem{ Text = "Tuesday", Value ="Tue"},
                         new SelectListItem{ Text = "Wednesday", Value ="Wed"},
                          new SelectListItem{ Text = "Thursday", Value ="Thu"},
                           new SelectListItem{ Text = "Friday", Value ="Fri"},
                            new SelectListItem{ Text = "Saturday", Value ="Sat"},
                             new SelectListItem{ Text = "Sunday", Value ="Sun"}

                    }, "Select Day", new { htmlAttributes = new { @class = "dropdown dropdown-menu" } })
            @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
        </div>
    </div>
   
    <br />
    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="CREATE NEW CLASS" class="btn btn-default" style="font-size:15px" />
        </div>
    </div>
</div>

}

<div>
    @Html.ActionLink("Back to List", "TimetableList")
</div>

@section Scripts {
    
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Views/Timetable/DeleteTimetable.cshtml
@model Project.Models.Timetable

@{
    ViewBag.Title = "DeleteTimetable";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete Class</h1>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel=" stylesheet" href="~/Content/bootstrap.css">
    <link rel=" stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>

<h3>Are you sure you want to delete this?</h3>
<div >
  
    <hr />
    <dl class="dl-horizontal" style="font-size:15px">
        <dt>
            @Html.DisplayNameFor(model => model.classId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.classId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hall)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="DELETE" class="btn btn-default" style="font-size:15px"/> |
            @Html.ActionLink("Back to List", "TimetableList")
        </div>
    }
</div>

Project/Views/Timetable/EditTimetable.cshtml
@model Project.Models.Timetable

@{
    ViewBag.Title = "EditTimetable";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Class Details</h1>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel=" stylesheet" href="~/Content/bootstrap.css">
    <link rel=" stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal" style="font-size:15px">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Subject, ViewBag.Subjects as SelectList, "Select Grade", new { htmlAttributes = new { @class = "form-control col-md-10" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>
   
    <div class="form-group">
        @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Grade, ViewBag.Grades as SelectList, "Select Grade", new { htmlAttributes = new { @class = "form-control col-md-10" } })
            @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TeacherName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TeacherName, ViewBag.teacherlist as SelectList, "Select Teacher", new { htmlAttributes = new { @class = "form-control col-md-10" } })
            @Html.ValidationMessageFor(model => model.TeacherName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hall, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Hall", new List<SelectListItem>
                    {
                        new SelectListItem{ Text = "H1", Value ="H1"},
                        new SelectListItem{ Text = "H2", Value ="H2"},
                         new SelectListItem{ Text = "H3", Value ="H3"}
                    }, "Select Hall", new { htmlAttributes = new { @class = "dropdown dropdown-menu" } })
            @Html.ValidationMessageFor(model => model.Hall, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Day", new List<SelectListItem>
                    {
                        new SelectListItem{ Text = "Monday", Value ="Mon"},
                        new SelectListItem{ Text = "Tuesday", Value ="Tue"},
                         new SelectListItem{ Text = "Wednesday", Value ="Wed"},
                          new SelectListItem{ Text = "Thursday", Value ="Thu"},
                           new SelectListItem{ Text = "Friday", Value ="Fri"},
                            new SelectListItem{ Text = "Saturday", Value ="Sat"},
                             new SelectListItem{ Text = "Sunday", Value ="Sun"}

                    }, "Select Day", new { htmlAttributes = new { @class = "dropdown dropdown-menu" } })
            @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <br />
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="SAVE CHANGES" class="btn btn-default" style="font-size:15px" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "TimetableList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Views/Timetable/TimetableDetails.cshtml
@model Project.Models.Timetable

@{
    ViewBag.Title = "TimetableDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Class Details</h1>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel=" stylesheet" href="~/Content/bootstrap.css">
    <link rel=" stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<div style="font-size:15px">

    <hr />
    <br />
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.classId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.classId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hall)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditTimetable", new {  id = Model.classId }) |
    @Html.ActionLink("Back to List", "TimetableList")
</p>

Project/Views/Timetable/TimetableList.cshtml
@model IEnumerable<Project.Models.Timetable>

@{
    ViewBag.Title = "TimetableList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel=" stylesheet" href="~/Content/bootstrap.css">
    <link rel=" stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<h1>Classes List</h1>


<p>
    @Html.ActionLink("Create New", "CreateTimeTable")
</p>
<body>


    <div>
        @using (Html.BeginForm("TimetableList", "Timetable", FormMethod.Get))
        {
            @Html.TextBox("searching")<Input type="submit" value="Search" />
        }
    </div>
    <br />
    <br />
    <table class="table" style="font-size:15px">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Day)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hall)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeacherName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Subject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hall)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TeacherName)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditTimetable", new { id = item.classId }) |
            @Html.ActionLink("Details", "TimetableDetails", new { id = item.classId }) |
            @Html.ActionLink("Delete", "DeleteTimetable", new { id = item.classId })
        </td>
    </tr>
        }

    </table>
</body>
<br />
<br />

Project/Views/Timetable/Timetablehome.cshtml
@{
    ViewBag.Title = "Timetablehome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CLASS MANAGEMENT</h1>

<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel=" stylesheet" href="~/Content/bootstrap.css">
    <link rel=" stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<br/>
<br />
<br />
<br />
<body>
    <div >
        <a button style="padding: 15px 60px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;border-radius: 12px;background-color:#e7e7e7 ;" href ="CreateTimetable">ADD NEW CLASS</button></a>
        <br/>
        <br/>
        <br/>
        <a button style="padding: 15px 60px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;border-radius: 12px;background-color: #e7e7e7;"href ="Timetablelist">CLASS DETAILS</button></a>
        <br/>
        <br/>
        <br/>
        <a button style="padding: 15px 60px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;border-radius: 12px;background-color: #e7e7e7;color:cornflowerblue;" @Html.ActionLink("Report ", "Reports")</button></a>
        <br/>
    </div>
</body>
<br/>
<br />