Project/Models/TeacherList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherList()
        {
            this.SubjectTBs = new HashSet<SubjectTB>();
        }
    
        public string Username { get; set; }
        public string TeacherName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectTB> SubjectTBs { get; set; }
    }
}

Project/Controllers/PayRollController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using System.Data.Sql;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Reporting.WebForms;
using System.Data.Entity.Validation;

namespace TutionClassManagmentSystem.Controllers
{
    public class PayRollController : Controller
    {
        public ActionResult Payment()
        {
            return View();
        }

        // GET: PayRoll
        public ActionResult TeacherList(String searching)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.Teachers.Where(x => x.Name.StartsWith(searching) || searching == null).ToList());
            }
        }


        /// <summary>
        /// GET:Add Teacher
        /// </summary>
        /// <returns></returns>
        public ActionResult Add_teacher_salary(int id)
        {


            string date = DateTime.Now.ToString("MM/dd/yyyy hh:mm tt");
            string month = DateTime.Now.ToString("MMMM");

            DBmodel payrollentities = new DBmodel();
            Teacher teacher = payrollentities.
                Teachers.SingleOrDefault(x => x.UserID == id);

            TeacherSalaryView teachersalaryView = new TeacherSalaryView();
            teachersalaryView.TeacherID = teacher.UserID;
            teachersalaryView.Name = teacher.Name;
            teachersalaryView.Month = month;
            teachersalaryView.Date_Time = date;

            return View(teachersalaryView);
        }


        ////
        ///POST: Add Teacher
        ///
        [HttpPost]
        public ActionResult Add_teacher_salary(int id, TeacherSalary teacherSalary)
        {
            try
            {
                using (DBmodel payrollentities = new DBmodel())
                {
                    payrollentities.TeacherSalaries.Add(teacherSalary);
                    payrollentities.SaveChanges();
                }

                return RedirectToAction("Salary_details_teacher");
            }
            catch
            {
                return View();
            }

        }



        public ActionResult Salary_details_teacher(string searching)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.TeacherSalaries.Where(x => x.Name.StartsWith(searching) || searching == null).ToList());
            }
        }

        public ActionResult Salary_delete_teacher(int id)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.TeacherSalaries.Where(x => x.SalaryId == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult Salary_delete_teacher(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (DBmodel payrollentities = new DBmodel())
                {
                    TeacherSalary teacherSalary = payrollentities.TeacherSalaries.Where(x => x.SalaryId == id).FirstOrDefault();
                    payrollentities.TeacherSalaries.Remove(teacherSalary);
                    payrollentities.SaveChanges();
                }
                return RedirectToAction("Salary_details_teacher");
            }
            catch
            {
                return View();
            }


        }
        public ActionResult Salary_edit_teacher(int id)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.TeacherSalaries.Where(x => x.SalaryId == id).FirstOrDefault());
            }
        }

        [HttpPost]
        public ActionResult Salary_edit_teacher(int id, TeacherSalary teacherSalary)
        {
            try
            {

                using (DBmodel payrollentities = new DBmodel())
                {

                    payrollentities.Entry(teacherSalary).State = EntityState.Modified;
                    payrollentities.SaveChanges();
                }
                return RedirectToAction("Salary_details_teacher");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Salary_details_single_teacher(int id)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.TeacherSalaries.Where(x => x.SalaryId == id).FirstOrDefault());
            }

        }

        /// <summary>
        /// Student Fee
        /// </summary>
        /// <param name="searching"></param>
        /// <returns></returns>
        public ActionResult StudentList(String searching)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.StudentTBs.Where(x => x.fullname.StartsWith(searching) || searching == null).ToList());

            }
        }

        /// <summary>
        /// GET:Add Student
        /// </summary>
        /// <returns></returns>
        public ActionResult Add_student_fee(int id)
        {


            string date = DateTime.Now.ToString("MM/dd/yyyy hh:mm tt");
            string month = DateTime.Now.ToString("MMMM");

            DBmodel payrollentities = new DBmodel();
            StudentTB studentTB = payrollentities.
                        StudentTBs.SingleOrDefault(x => x.sid == id);

            StudentFeeView studentFeeView = new StudentFeeView();
            studentFeeView.StudentID = studentTB.sid;
            studentFeeView.Name = studentTB.fullname;
            studentFeeView.Subject = studentTB.subject;
            studentFeeView.Month = month;
            studentFeeView.Date_Time = date;

            return View(studentFeeView);
        }

        ////
        ///POST: Add Student
        ///
        [HttpPost]
        public ActionResult Add_student_fee(int id, StudentFee studentFee)
        {
            try
            {
                using (DBmodel payrollentities = new DBmodel())
                {
                    payrollentities.StudentFees.Add(studentFee);
                    payrollentities.SaveChanges();
                }

                return RedirectToAction("Fee_details_students");
            }
            catch
            {
                return View();
            }

        }

        public ActionResult Fee_details_students(string searching)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.StudentFees.Where(x => x.Name.StartsWith(searching) || searching == null).ToList());
            }
        }

        public ActionResult Fee_delete_student(int id)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.StudentFees.Where(x => x.SalaryId == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult Fee_delete_student(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (DBmodel payrollentities = new DBmodel())
                {
                    StudentFee studentFee = payrollentities.StudentFees.Where(x => x.SalaryId == id).FirstOrDefault();
                    payrollentities.StudentFees.Remove(studentFee);
                    payrollentities.SaveChanges();
                }
                return RedirectToAction("Fee_details_students");
            }
            catch
            {
                return View();
            }


        }
        public ActionResult Fee_edit_student(int id)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.StudentFees.Where(x => x.SalaryId == id).FirstOrDefault());
            }
        }

        [HttpPost]
        public ActionResult Fee_edit_student(int id, StudentFee studentFee)
        {
            try
            {

                using (DBmodel payrollentities = new DBmodel())
                {

                    payrollentities.Entry(studentFee).State = EntityState.Modified;
                    payrollentities.SaveChanges();
                }
                return RedirectToAction("Fee_details_students");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Fee_details_single_student(int id)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.StudentFees.Where(x => x.SalaryId == id).FirstOrDefault());
            }
        }

        public ActionResult CleanerList(String searching)
        {
            using (DBmodel payrollentities = new DBmodel())
            {
                return View(payrollentities.Cleaners.Where(x => x.Name.StartsWith(searching) || searching == null).ToList());
            }
        }
        /// <summary>
        /// GET:Add Cleaner
        /// </summary>
        /// <returns></returns>
        public ActionResult Add_cleaner_salary(int id)
        {


            string date = DateTime.Now.ToString("MM/dd/yyyy hh:mm tt");
            string month = DateTime.Now.ToString("MMMM");

            DBmodel payrollentities = new DBmodel();
            Cleaner cleaner = payrollentities.
                        Cleaners.SingleOrDefault(x => x.UserID == id);

            CleanerSalaryView cleanerSalaryView = new CleanerSalaryView();
            cleanerSalaryView.CleanerID = cleaner.UserID;
            cleanerSalaryView.Name = cleaner.Name;
            cleanerSalaryView.Month = month;
            cleanerSalaryView.Date_Time = date;

            return View(cleanerSalaryView);
        }

        ////
        ///POST: Add Cleaner
        ///
        [HttpPost]

Project/Views/PayRoll/Add_office_salary.cshtml
@model Project.Models.OfficeSalaryView

@{
    ViewBag.Title = "Add_office_salary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal" style="font-size:15px">
    <h4 class="display-3">Add Office Staff Salary</h4>
    <hr />
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.OfficeID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OfficeID, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Time, new { htmlAttributes = new { @class = "form-control",style = "font-size:15px" } })

            </div>
        </div>
</div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" style="font-size:15px" />
            </div>
        </div>
 }

    <div>
        @Html.ActionLink("Back to List", "OfficeList")
    </div>

Project/Views/PayRoll/Add_student_fee.cshtml
@model Project.Models.StudentFeeView

@{
    ViewBag.Title = "Add_student_fee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal" style="font-size:15px">
    <h4 class="display-3">Add Student Fee</h4>
    <hr />
    <br />
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date_Time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date_Time, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" style="font-size:15px" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "StudentList")
</div>

Project/Views/PayRoll/CleanerList.cshtml
@model IEnumerable<Project.Models.Cleaner>

@{
    ViewBag.Title = "CleanerList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body style="padding: 10px">
    <p class="display-1">Cleaner Staff Details</p>
    <button style="font-size:20px;color:black">
        @Html.ActionLink("Show Salary Details", "Salary_details_cleaner")
    </button>
    <br />
    <br />

    <div style="font-size:15px">
        @using (Html.BeginForm("CleanerList", "PayRoll", FormMethod.Get))
        {
            @Html.TextBox("searching")<input type="submit" value="Search" />
        }
    </div>
    <br />
    <table class="table table-hover" style="font-size:15px;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserID)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserID)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @Html.ActionLink("Add New", "Add_cleaner_salary", new { id = item.UserID })

                </td>
            </tr>
        }

    </table>
</body>

<br />
<br />
<br />
<br />
<br />
<br />
<br />

Project/Views/PayRoll/CreateAccount_bill.cshtml
@model Project.Models.Biil

@{
    ViewBag.Title = "CreateAccount_bill";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal" style="font-size:15px">
        <h4 class="display-3">Add Billing Details</h4>
        <hr />
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Payment_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Payment_Name, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
                @Html.ValidationMessageFor(model => model.Payment_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" style="font-size:15px" />
            </div>
        </div>
    </div>
}

<div  style="font-size:15px">
    @Html.ActionLink("Back to List", "BillList")
</div>

Project/Views/PayRoll/DeleteDetails_bill.cshtml
@model Project.Models.Biil

@{
    ViewBag.Title = "DeleteDetails_bill";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<h3 class="display-3">Are you sure you want to delete Payment <b><u> @Html.DisplayFor(model => model.Payment_Name)</u></b> </h3>
<div>
  <br />
    <hr />
    <dl class="dl-horizontal"  style="font-size:20px;border-style: solid;">
        <dt>
            Bill Id
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillId)
        </dd>

        <dt>
            Payment Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment_Name)
        </dd>

        <dt>
           Amount
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
    <br />
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color"  style="font-size:15px">
            <input type="submit" value="Delete" class="btn btn-default"style = "font-size:15px" /> |
            @Html.ActionLink("Back to List", "BillList", new { htmlAttributes = new {style = "font-size:15px" } })
        </div>
    }
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

Project/Views/PayRoll/EditDetails_bill.cshtml
@model Project.Models.Biil

@{
    ViewBag.Title = "EditDetails_bill";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="font-size:15px">
        <h4 class="display-3">Edit Bill Details</h4>
        <hr />
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BillId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillId, new { htmlAttributes = new { @class = "form-control" ,style = "font-size:15px" } })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Payment_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Payment_Name, new { htmlAttributes = new { @class = "form-control" ,style = "font-size:15px" } })
                @Html.ValidationMessageFor(model => model.Payment_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", style = "font-size:15px" } })
                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" style="font-size:15px"/>
            </div>
        </div>
    </div>
}

<div style="font-size:15px">
    @Html.ActionLink("Back to List", "BillList")
</div>

Project/Views/PayRoll/Salary_delete_office.cshtml
@model Project.Models.OfficeSalary

@{
    ViewBag.Title = "Salary_delete_office";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<h3 class="display-3">Are you sure you want to delete SalaryId <b><u> @Html.DisplayFor(model => model.SalaryId)</u></b> </h3>
<div>
    <br />
    <hr />
    <dl class="dl-horizontal" style="font-size:20px;border-style: solid;">
        <dt>
            @Html.DisplayNameFor(model => model.SalaryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalaryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfficeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfficeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Time)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="font-size:15px">
            <input type="submit" value="Delete" class="btn btn-default" style="font-size:15px" /> |
            @Html.ActionLink("Back to List", "Salary_details_cleaner", new { htmlAttributes = new { style = "font-size:15px" } })
        </div>
    }
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

Project/Views/PayRoll/Salary_details_teacher.cshtml
@model IEnumerable<Project.Models.TeacherSalary>

@{
    ViewBag.Title = "Salary_details_teacher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

</head>
<body style="padding: 10px">
    <p class="display-1">Teacher Salary Details</p>
    <button style="font-size:20px;color:black">
        @Html.ActionLink("Back to Teacher List", "TeacherList")
    </button>
    <button style="font-size:20px;color:black">
        @Html.ActionLink("Main menu", "Payment")
    </button>
    <button style="font-size:20px;color:black">
        Total Amount: @Model.Sum(i => i.Amount)
    </button>
    <br />
    <br />

    <div style="font-size:15px">
        @using (Html.BeginForm("Salary_details_teacher", "PayRoll", FormMethod.Get))
        {
            @Html.TextBox("searching")<input type="submit" value="Search" />
        }
    </div>
    <br />
    <table class="table table-hover" style="font-size:15px;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SalaryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeacherID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Month)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date_Time)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SalaryId)
                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TeacherID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Month)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Time)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Salary_edit_teacher", new { id = item.SalaryId }) |
                    @Html.ActionLink("Details", "Salary_details_single_teacher", new { id = item.SalaryId }) |
                    @Html.ActionLink("Delete", "Salary_delete_teacher", new { id = item.SalaryId })
                </td>
            </tr>
        }

    </table>
    <div>

    </div>
</body>
<br />
<br />
<br />
<br />
<br /><br />
<br />